name: Build LaTeX document
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile application
        uses: xu-cheng/latex-action@v2
        with:
          root_file: application.tex
      - name: Compile attachments
        uses: xu-cheng/latex-action@v2
        with:
          root_file: application_attachments.tex
      - name: Move to deploy directory
        run: |
          mv application.pdf deploy/application.pdf
          mv application_attachments.pdf deploy/application_attachments.pdf
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: deploy/

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
